linuxmint/nemo

src/nemo-window-menus.c
Also makes it look nicer on hidpi screens
=> Use symbolic icon for terminal in toolbar

src/nemo-bookmark-list.c, src/nemo-bookmark-list.h, src/nemo-bookmarks-window.c, src/nemo-bookmarks-window.glade
This adds a new public function to the NemoBookmarkList API which allows
sorting bookmarks in ascending order. The function is used in the
"clicked" callback of a new sort button added to the bookmarks window.
Signed-off-by: Niklas Koep <niklas.koep@gmail.com>
=> Make bookmarks sortable

src/nemo-window-menus.c
=> Nemo Toolbar: Change the rest of the icons to symbolic

eel/eel-canvas.c, eel/eel-editable-label.c, eel/eel-glib-extensions.c, libnemo-private/nemo-file.c, libnemo-private/nemo-icon-canvas-item.c, libnemo-private/nemo-icon-container.c, libnemo-private/nemo-icon-dnd.c, libnemo-private/nemo-icon-info.c, libnemo-private/nemo-tree-view-drag-dest.c, libnemo-private/nemo-widget-menu-item.c, src/nemo-application.c, src/nemo-pathbar.c, src/nemo-properties-window.c, src/nemo-view.c, src/nemo-window-menus.c, src/nemo-window-slot-dnd.c, src/nemo-window.c, src/nemo-x-content-bar.c
A set of minor changes mainly to remove some unnecessary code.  Also replaced calls to gtk_icon_info_free which is deprecated.    Still getting my head round the git branching, so apologies if this is not as focussed as would be ideal.
=> Minor changes, mainly removing unnecessary code. Replaced one deprecated function.

data/new-launcher.nemo_action.in, src/nemo-directory-view-ui.xml
-Only show "Create new Launcher" on the desktop
-Remove "Show Hidden Files" from the right click menu altogether, but it still exists in Menu>View
=> Clean up background context menu some more

cut-n-paste-code/libegg/Makefile.am, eel/Makefile.am, libnemo-extension/Makefile.am, libnemo-private/Makefile.am, src/Makefile.am, test/Makefile.am
Redo deleted commit
https://github.com/linuxmint/nemo/pull/524
=> update for newer autoconf

libnemo-private/Makefile.am, libnemo-private/nemo-file-operations.c, libnemo-private/nemo-job-queue.c, libnemo-private/nemo-job-queue.h, libnemo-private/nemo-progress-info-manager.c, libnemo-private/nemo-progress-info.c, libnemo-private/nemo-progress-info.h, src/nemo-progress-info-widget.c, src/nemo-progress-info-widget.h, src/nemo-progress-ui-handler.c
- widget needs more work, not happy with it entirely yet
=> File operations queueing

libnemo-private/nemo-action.c, libnemo-private/nemo-action.h, src/nemo-action-config-widget.c, src/nemo-action-config-widget.h, src/nemo-extension-config-widget.c, src/nemo-extension-config-widget.h, src/nemo-script-config-widget.c, src/nemo-script-config-widget.h
In this PR the globals and definitions already defined are used.
=> Remove redundant literals

libnemo-private/nemo-file-operations.c, libnemo-private/nemo-file-utilities.c, libnemo-private/nemo-file.c
Fixes #1060
Fixes #208
Probably fixes these as well, but there is not enough information available to know for sure:
Fixes #457
Fixes #792
Fixes #1024
=> Pull a few fixes for trash from nautilus

libnemo-private/nemo-query.c, src/nemo-query-editor.c, src/nemo-query-editor.h, src/nemo-window-pane.h, src/nemo-window-slot.c, src/nemo-window-slot.h, src/nemo-window.c
This is the next chunk of Nautilus search commits. 
See commit messages.
=> [3.0] Nautilus search commits

src/nemo-icon-view-container.c
Fixes: https://github.com/linuxmint/nemo/issues/1032
=> Compact View: Removed condition that disables thumbnails

src/nemo-properties-window.c
Use a stack instead of notebook
Implements feature request #1009
=> New style tabs for "Properties" window

src/nemo-application.c
=> nemo-application: don't try to close blank desktop windows

libnemo-private/nemo-file-operations.c, src/nemo-application.c, src/nemo-blank-desktop-window.c
This fixes some warnings, since #987
=> Warning fix

src/nemo-view.c
=> Fix printf format specifier

src/nemo-desktop-window.c, src/nemo-places-sidebar.c, src/nemo-window.c
@clefebvre @mtwebster Replaces #1131
=> GTK 3.20 :: Add style classes to nemo's window, desktop window, and sidebar

data/extract_action_strings, data/merge_action_strings, files/usr/share/nemo/actions/myaction.py
All scripts now Python 2-3 compatible:
- /data/extract_action_strings
- /data/merge_action_strings
- /files/usr/share/nemo/actions/myaction.py
=> Port python scripts to Python 3

src/nemo-file-management-properties.c, src/nemo-file-management-properties.glade
=> Set minimum size for File Management Preferences window

src/nemo-notebook.c
based on
https://git.gnome.org/browse/nautilus/commit/?id=4e0cf5e6e9ec6db4099f1f8581fac2b3a9c52cc0
=> notebook: removed unused ifdef code

libnemo-private/nemo-directory-async.c, libnemo-private/nemo-directory-private.h, libnemo-private/nemo-directory.c, libnemo-private/nemo-file-private.h, libnemo-private/nemo-file.c, libnemo-private/nemo-file.h, libnemo-private/nemo-global-preferences.h, libnemo-private/org.nemo.gschema.xml.in, src/nemo-file-management-properties.c, src/nemo-file-management-properties.glade, src/nemo-icon-view-container.c
This doesn't actually fix #954, it removes the feature entirely. The issue may as well be closed, though, if nobody wants to re-implement it as the gtk features it depends on do nothing since gtk 3.13
Edit: I'm dumb and the issue is actually already closed.
=> remove "Show text in icon" preference

libnemo-private/nemo-file.c
=> nemo-file.c: don't show count in tooltip if count is disabled

libnemo-private/nemo-trash-monitor.c
When emptying trash bin with a large amount of files it causes  nemo/gvfsd-trash  to hogs the CPU
should fix https://github.com/linuxmint/nemo/issues/925
based on
https://git.gnome.org/browse/nautilus/commit/?id=a99b4cf8f1163a2ef8a6cd1d713482978deebf7b
and
https://git.gnome.org/browse/nautilus/commit/libnautilus-private/nautilus-trash-monitor.c?h=gnome-3-20&id=7c72858b6505f59538b5d196ae318d2f826e2f94
=> trash-monitor: change trash monitoring process

libnemo-private/nemo-icon-container.c, src/nemo-desktop-icon-view.c, src/nemo-style-application.css
Fixes https://github.com/linuxmint/nemo/issues/1231
=> Fix GTK 3.21.3 desktop redraw issue (#1231)

libnemo-private/nemo-icon-container.c
This expands the grid spacing to fit the container, as seen [here](https://gfycat.com/CleverHappygoluckyArawana).
=> Expand grid width to canvas size

libnemo-private/nemo-file-undo-operations.c
Based on https://git.gnome.org/browse/nautilus/patch/?id=d1fdc58be0731578572d17fb9c2992b22fab9bbb
=> file-undo-operations: change trashed files matching condition

configure.ac
=> raise tracker version

src/nemo-navigation-action.c
Adjust the event handler of the toolbar buttons "Back", "Forward" and "Up" to handle middle clicks.
The following changes were performed in the file `nemo-navigation-action.c`:
- `tool_button_press_cb` has been extended to call the new function `new_tab_action`, if the button id is `2` and the event type is "pressed" (otherwise, double clicking with the middle mouse button causes `new_tab_action` to be called three times).
- `new_tab_action`: Similar to `show_menu`, the behavior is dependent on the navigation direction. This function reuses already existing functions from existing event handlers. To open new tabs, the `NEMO_WINDOW_OPEN_FLAG_NEW_TAB` flag is used when calling the aforementioned methods.
Proposed implementation of the feature request #1062.
P.S. This is my first pull …
=>  Middle click on parent/previous/next folder

src/nemo-blank-desktop-window.c, src/nemo-desktop-window.c, src/nemo-desktop-window.h
Always handle it in a class handler.
Nautilus commit c00d47b32c60869d6dcdfd1e15368b3a22ac3fcb
=> window: cleanup delete-event handling

libnemo-private/nemo-search-engine-simple.c
This allows wildcard search in nemo (with search-engine-simple), it is fully backwards compatible (an old search string will match exactly the same files). It does not use any additional external libs etc.
Implemented now:
- \* wildcard for zero or more unknown characters
- ? wildcard for exactly one unknown character
- Characters can be escaped using \
What will work now:
"img_*.jpg" will for example match "img_a.jpg", "IMG_1234.JPG" and so on...
If no wildcard/escape is used the old comparison is used, so no performance decrease (just one additional if per search word during the comparison).
If at least one wildcard/escape is used, the search words are combined with logic OR, otherwise logic AND like before (with wildcards OR is more useful IMHO, AND is default for non-wildcard to not …
=> wildcard search for search-engine-simple

eel/eel-string.c, eel/eel-string.h, files/usr/share/gtksourceview-2.0/language-specs/nemo_action.lang, files/usr/share/gtksourceview-3.0/language-specs/nemo_action.lang, files/usr/share/nemo/actions/sample.nemo_action, libnemo-private/nemo-action.c, libnemo-private/nemo-action.h
=> Actions: escape quotes in file paths, add a Terminal option to spawn in a new window

libnemo-private/nemo-icon-private.h
save a little memory use by rearranging the fields to avoid memory padding
in structures
=> nemo-icon-private.h: avoid memory padding

docs/nemo.1
https://github.com/linuxmint/nemo/issues/1599
=> update man page for nemo

libnemo-private/nemo-global-preferences.h, libnemo-private/org.nemo.gschema.xml.in, src/nemo-file-management-properties.c, src/nemo-file-management-properties.glade, src/nemo-toolbar.c
=> nemo-toolbar.c: Add option to hide elevated privileges warning.

libnemo-private/nemo-file.c
and one message about deceptive indentation
=> nemo-file: fix a couple of signed/unsigned warnings

src/nemo-file-management-properties.c, src/nemo-file-management-properties.glade
Added options to preview thumbnails for up to 16GB and 32GB
=> Resolves #1181 (Bigger thumbnail size preview)

libnemo-private/nemo-desktop-metadata.c, libnemo-private/nemo-file-operations.c, src/nemo-convert-metadata.c
a little more invasive than most of the other simple changes for compile warnings
=> remove some signed/unsigned compiler warnings

libnemo-private/nemo-file.c
Note:  the warnings highlight one definite bug, which I have marked with a FIXME and will
return to in a later change
=> nemo-file: resolve a number of compiler warnings

src/nemo-location-entry.c, src/nemo-notebook.c, src/nemo-query-editor.c
Most icons in the toolbar are symbolic icons except these, so change them.
=> Use symbolic icons

src/nemo-window.c
https://github.com/GNOME/nautilus/commit/4b135947939f2d1a7530900be5af21127bdb11aa
crash avoidance
=> nemo-window: check for an active slot when updating cursor

src/nemo-properties-window.c
https://github.com/GNOME/nautilus/commit/bb002736e79ad3a2cd4b80deb5efc22c4c075a93
=> nemo-properties-window: use utility functions if available

data/org.nemo.root.policy.in
The current message is untranslated.
=> Change polkit policy message to "Files"

libnemo-extension/meson.build
Make the extension variable path relative.
=> Fix some issues with pkgconfig file

eel/eel-editable-label.c, eel/eel-string.c, src/nemo-desktop-icon-grid-view.c, src/nemo-desktop-icon-view.c, src/nemo-icon-view.c, src/nemo-mime-actions.c, src/nemo-tree-sidebar.c, src/nemo-window.c
=> move code after early return statements where possible

libnemo-private/nemo-global-preferences.c
I swore I wouldn't contribute to this project again but I can hardly fork just for this so joke's on me I guess. Good job with nemo otherwise! ;)
=> Fix nemo_global_preferences_get_size_prefix_preference getting set to the wrong value

libnemo-private/nemo-file-utilities.c
=> Fallback to uri when path is null in title

libnemo-private/nemo-action-manager.c
Fix for https://github.com/linuxmint/nemo/issues/2183
I did not author this, but I implemented the code pasted on the issue page, visually reviewed it, and tested it on my machine - seems to work.
THANK YOU to @SEGGER-Alex for the solution!
=> Sort nemo actions menu alphabetically

src/nemo-view.c
Depends on https://github.com/linuxmint/xapps/pull/90
=> [WIP] nemo action: use different icons for pin/unpin

src/nemo-properties-window.c
closes #2408
based on https://gitlab.gnome.org/GNOME/nautilus/-/merge_requests/409/diffs
=> display last modified date property on directories

libnemo-private/nemo-file.c
This PR resolves #942. 
Added entry for "application-x-generic" when checking for the given file's type.
=> Fixes issue 942. Adds check for generic x applications

src/nemo-pathbar.c
Freeing volume_monitor per GIO documentation.
=> Fixing small memory leak.

libnemo-private/nemo-icon-canvas-item.c
Alerted by Ninja build to variable being set, but never used.
=> Removes unused variable

src/nemo-window.c
=> Blocks operations while renaming.

libnemo-private/nemo-icon-names.h, src/nemo-places-sidebar.c
depends on https://github.com/linuxmint/xapp/pull/119
=> change favorites icon

libnemo-private/nemo-icon-container.c
=> Remove type-ahead search on mouse click

src/nemo-window-menus.c
=> Fixes 666. Hide menu items when root

libnemo-private/nemo-file-operations.c
Based on https://github.com/GNOME/nautilus/commit/36e505c12ce7057e444d929c96ac810ce85192e7
=> file-operation: Prevent recursion to speed up emptying trash

libnemo-private/nemo-file-operations.c
Based on
https://github.com/GNOME/nautilus/commit/f03cb9f79a2f005326834dc082dfbae4e0a4b786
https://github.com/GNOME/nautilus/commit/c028e48e589d07360c7ea8939a7b334948ca0e0c
https://github.com/GNOME/nautilus/commit/d771158b83385029836a15a345e05fdda76795f2
=> Improve MS filesystem handling

libnemo-private/nemo-icon-canvas-item.c
Fixes https://github.com/linuxmint/cinnamon/issues/9766
=> Fix desktop bold fonts

src/nemo-desktop-overlay.c
=> Fixes issue with desktop sort not saving

libnemo-private/nemo-file.c
=> Sets correct values for x and y for file->details->cached_position

src/nemo-window.c
=> Issue 2666. Blocks emoji chooser from breaking Nemo

libnemo-private/nemo-progress-info.c
=> Increases emit time of change for progress update

gresources/nemo-shortcuts.ui, src/nemo-window-menus.c
=> Adds keyboard shortcut for Same Location as Other Pane.

src/nemo-window-menus.c
=> Enables F6 to immediately toggle between panes

src/nemo-places-sidebar.c
=> Fixes 2696. Detects if Trash is supported.

src/nemo-bookmark-list.c
Clean up do_finalize method. Use NemoBookmarkList instead
of casting itself every line.
Also, properly free the GFileMonitor when it isn't neccessary.
g_file_monitor_cancel() doesn't free the object.
Taken from:
https://github.com/GNOME/nautilus/commit/ec4241a80b029d0bb13d3f95a963d5f7bd5acd1a
https://github.com/GNOME/nautilus/commit/179e0bfaddcf29d8a7f8074cc924d5aa45b1a954
=> bookmark-list: Clean up and close memory leak

src/nemo-location-bar.c
=> Removes spaces from Samba drive paths

src/nemo-location-entry.c
=> Fixes #2244. Checks for leading space when setting the location entry

debian/control, search-helpers/meson.build, search-helpers/mso-xls.nemo_search_helper, search-helpers/nemo-xls-to-txt, search-helpers/third-party/meson.build
=> search: Use the python xlrd module to read .xls files.

libnemo-private/nemo-global-preferences.c, libnemo-private/nemo-global-preferences.h, src/nemo-file-management-properties.c
=> Sync sort-directories-first with gtk file chooser

src/nemo-properties-window.c
In the properties window of multiple files and directories, split the number of elements and their total size into separate rows. Also always display the (total) file size in the long format (i.e. incl. the number of bytes).
This is quite hacky and there are many special cases, so please let me know if you have any suggestions or improvements.
Fixes #2786
=> properties-window: split dir elem count and size

src/nemo-view.c
Discussion: linuxmint/discussions#114
=> nemo-view.c: Show detailed actions for some selection types
