- src/nemo-statusbar.c
The Mint-X theme will need a small tweak to work with this.
Edit:
Companion fix for the Mint-X theme: https://github.com/linuxmint/mint-themes-gtk3/pull/41
> fix the growing size of the nemo statusbar in each new version of gtk

- src/nemo-file-management-properties.c
- src/nemo-file-management-properties.glade
Raise thumbnail size limit to account for larger rip sizes of HD media.
> raise thumbnail size limit

- src/nemo-view.c
Cherry-picked from [this Nautilus commit](https://git.gnome.org/browse/nautilus/commit/?id=1a1fa464fd16f93d9a9fbb73b894f4f6c0a098f8), adapted for Nemo.
Fixes https://bugs.launchpad.net/bugs/1418141.
> Show icons for templates in the "create new document" menu

- eel/eel-canvas.c
- eel/eel-editable-label.c
- eel/eel-glib-extensions.c
- libnemo-private/nemo-file.c
- libnemo-private/nemo-icon-canvas-item.c
- libnemo-private/nemo-icon-container.c
- libnemo-private/nemo-icon-dnd.c
- libnemo-private/nemo-icon-info.c
- libnemo-private/nemo-tree-view-drag-dest.c
- libnemo-private/nemo-widget-menu-item.c
- src/nemo-application.c
- src/nemo-icon-view.c
- src/nemo-pathbar.c
- src/nemo-properties-window.c
- src/nemo-view.c
- src/nemo-window-menus.c
- src/nemo-window-slot-dnd.c
- src/nemo-window.c
- src/nemo-x-content-bar.c
gdk_display_get_n_screens always returns 1, since GTK3.10, so calls to find the screen can be replaced by gdk_display_get_default_screen
> remove deprecated function gdk_display_get_n_screens

- src/nemo-properties-window.c
This Pull request improved the display of long folder paths in the properties-window. 
The ellipsize is placed in the middle, because the path root and the topmost folder are most significant. 
A tooltip containing the entire path was also added.
> Properties window ellipsize

- libnemo-private/nemo-icon-container.c
- src/nemo-window-menus.c
- src/nemo-window-private.h
- src/nemo-window.c
This PR fixes a bug taht the location entry is not shown by the slash shortcut. 
It also adds the tilde and the numpad devide key as goto shortcuts. 
They are also assigned in the GtK file chooser for the same usage.
> Goto shortcuts

- debian/control
- debian/rules
Fixes:
```
dpkg-gencontrol: warning: Depends field of package libnemo-extension-dev: unknown substitution variable ${shlibs:Depends}
dpkg-gencontrol: warning: Depends field of package gir1.2-nemo-3.0: unknown substitution variable ${gir:Depends}
dpkg-gencontrol: warning: Depends field of package gir1.2-nemo-3.0: unknown substitution variable ${shlibs:Depends}
W: nemo source: ancient-standards-version 3.9.2 (current is 3.9.5)
E: nemo source: not-binnmuable-any-depends-all nemo -> nemo-data
E: nemo-data: python-script-but-no-python-dep usr/share/nemo/actions/myaction.py
```
> Debian packaging: small fixes

- configure.ac
```
$ nemo
Initializing nemo-dropbox 2.4.0
nemo: symbol lookup error: nemo: undefined symbol: gnome_desktop_thumbnail_cache_check_permissions
```
> update cinnamon-desktop min version

- debian/control
nemo should have a versioned requirement for  libcinnamon-desktop4-2.6.1
> add runtime requirement for libcinnamon-desktop4

- libnemo-private/nemo-action-manager.c
- libnemo-private/nemo-action-manager.h
- libnemo-private/nemo-action.c
- libnemo-private/nemo-file-utilities.c
- libnemo-private/nemo-monitor.c
- src/nemo-action-config-widget.c
- src/nemo-interesting-folder-bar.c
- src/nemo-script-config-widget.c
- src/nemo-view.c
This PR replaces various string literals to build the scripts and actions path by function calls to a single place. I also removed the unused sys scripts path and fixes minor build issues that prevents to build the tree with Ubuntu Trusty.
> Scripts and actions path

- src/nemo-list-view.c
This fixes a bug that occurs when selecting a default sort method for list view. Selecting options from detailed type on down actually enables the next option in the drop down box.
Fixes #776, fixes #803, fixes #889
> Fix default sort order bug in list view

- src/nemo-connect-server-dialog.c
Fixes a bug where if the user first tries the SMB method, enters a domain, and then tries another method (e.g, ssh), the code would incorrectly prepend the domain to the username.
> Only include the domain if the method is SMB (bugfix)

- data/add-desklets.nemo_action.in
- data/change-background.nemo_action.in
- data/set-as-background.nemo_action.in
- src/nemo-action-config-widget.c
This PR shows the action comments in the action config view. 
This is a workaround to distinguish for actions with the same name, but different conditions. 
In this case the action autor can place different comments.
> Show tooltips in action config

- libnemo-private/nemo-search-directory.c
This is a long standing bug that hit me during testing. 
It happens if you open a saved search tree view in the list view. 
Btw.: I haven't known before that we are able to save searches. Maybe we can make the feature more prominent.
> Added search_is_not_empty, to fixe a segfault in treelist

- data/icons/Makefile.am
- data/icons/hicolor_actions_scalable_collapse-menu-symbolic.svg
- data/icons/hicolor_actions_scalable_expand-menu-symbolic.svg
- src/nemo-view.c
not ready... just concept - need to:
- always show all entries in pulldown menus
- only show widget in selection menu (not background click)
- small GC issue
> Add control to context menu to toggle simple/complex menu

- libnemo-private/nemo-directory-async.c
When getting the size of the root directory, nemo was descending
into other filesystems including /proc, causing it to report nonsensical
sizes.
Store the fsid of the starting directory, and do not recurse into
other mount points.
https://bugzilla.gnome.org/show_bug.cgi?id=629394
https://bugs.launchpad.net/ubuntu/+source/nautilus/+bug/585472
Based on Nautilus commit:
https://git.gnome.org/browse/nautilus/commit/?id=a645da5f1043c59203fd194fe85b6976d75d2ece
Original author:	Phillip Susi <psusi@ubuntu.com>
Fixes issue #1050.
> directory: limit deep scount (folder contents and size) to one filesystem

- src/nemo-view.c
Fixes issue #614
`g_app_info_create_from_commandline` eats the percent signs in file names with spaces. This doubles all percent signs.
This works better than `g_uri_unescape_string` as it still works on file-names with percent signs in them.
> Escape Percents in bulk rename

- src/nemo-notebook.c
```
At top level:
nemo-notebook.c:54:29: error: 'url_drag_types' defined but not used [-Werror=unused-const-variable]
static const GtkTargetEntry url_drag_types[] =
^~~~~~~~~~~~~~
```
> comment out unused define (needed for gcc-6.0)

- libnemo-private/nemo-file-operations.c
Changes the text from the default "Preparing" to "Emptying Trash" and pulses the progress info bar every 100 deletions.
> Improve appearance of job window for long running empty trash jobs

- src/nemo-application.c
- src/nemo-application.h
- src/nemo-desktop-manager.c
- src/nemo-desktop-manager.h
I have done this during my work merging the recent master changes into my Nautilus merge branch
https://github.com/linuxmint/nemo/pull/1041
Since I cannot compile master on stock Ubuntu, it is untested.
> reanable no-desktop command line option and add force-desktop

- src/nemo-blank-desktop-window.c
Currently all menu entries are displayed even though the dbus condition is not satisfied.
Here is the fix.
> Respect dbus_satisfied flag for menu enties on blank desktops

- src/nemo-window-manage-views.c
- src/nemo-window-slot.c
- src/nemo-window-types.h
same slot if this flag is passed to nemo_window_slot_open_location_full
to avoid opening a new window (and a crash) when starting a search
with the open in new window preference enabled
> nemo-window: add new flag NEMO_WINDOW_OPEN_FLAG_SEARCH and use the

- src/nemo-file-management-properties.glade
- src/nemo-window-pane.c
Those classes we used already for fedora 24 with gtk+-3.20.
http://pkgs.fedoraproject.org/cgit/rpms/nemo.git/tree/
nemo-window-pane is very useful to style everything under it, ie views, placesbar, ......, to avoid a long widget chain with gtk+-3.20.
nemo-properties-dialog i use for submarine themes from Mate to style the stack-switcher and to remove unwanted frame borders, which is side effect of using nodes with gtk+-3.20 changes .
Needed class nemo-window is already requested by another PR.
> add some style classes

- libnemo-private/nemo-desktop-utils.c
- libnemo-private/nemo-desktop-utils.h
- src/nemo-desktop-manager.c
If you clone (mirror) the two monitors, both desktops of both monitors are drawn on both monitors. 
This is no harm if the empty monitor is at index 1. If the primary monitor is on 1, the empty desktop is on top of the desktop icons and catches all mouse actions.
> Don't draw the desktop on a cloned monitor

- src/nemo-list-view.c
Fixes #1156 
So I figured out that `gtk_tree_view_column_get_button (l->data)` returned NULL after a column had been removed from the tree at line 1988 - this caused the segfault.
I'm suggesting to hide and show the columns instead of removing and adding them. This fixes the segfault for me and still allows to have different number of columns for different locations (e.g., Home and Trash as described in the issue).
> Fix segfault on changing the number of colums when in list view

- src/nemo-pathbar.c
Dynamically adding and removing these buttons was causing the visual style of buttons in the pathbar to break
> pathbar: Always show the pathbar up and down arrows.

- src/nemo-icon-view.c
- src/nemo-pathbar.c
https://github.com/linuxmint/nemo/commit/7f8245dbff1a61582d96f6aeff85bb2872553c5b - this header seems to have been missing since last year
https://github.com/linuxmint/nemo/commit/c0813b0e7e4f63c01bb150229c94ebe36d5b2c29 - we pass this gint16 to gtk where it specifies gint which triggers warnings. gtk seems to have always specified gint since the associated function was added in 3.0: https://developer.gnome.org/gtk3/3.0/GtkWidget.html#gtk-widget-get-preferred-width
> Avoid compiler warnings

- src/nemo-file-management-properties.c
- src/nemo-file-management-properties.glade
This improves a bit on https://github.com/linuxmint/nemo/commit/aa19ff3ebdb29781a7a3cbd701c589d67ac707c5
Since a large number of user settings such as translations, font-scaling, etc. can affect this, don't attempt to guess a minimum size. Instead get the size wanted by the stack switcher plus a small value to compensate for padding on the toolbar and use that to determine the minimum size instead.
> prefs: Don't try to hardcode a minimum size for the preferences dialog

- src/nemo-style-application.css
This set simply a background to this entry, other wise the font is hard to read if you rename a desktop icon, because you see simply the desktop bg.
It's better to set this here as in a theme.
Well, you can play around with the styling details but something like that you need to set.
> add standard settings for EelEditableLabel

- libnemo-private/nemo-desktop-directory.c
- libnemo-private/nemo-directory-async.c
- src/nemo-view.c
I'm seeing reports in fedora
https://bugzilla.redhat.com/attachment.cgi?id=1163002
caja had a similar issue
https://bugs.launchpad.net/ubuntu/+source/caja/+bug/1469784
Fix from caja
https://github.com/mate-desktop/caja/commit/883201a49341d588f5a6ffe2b7fd54676eb71019
> use g_hash_table_remove_all and get rid of some callbacks

- src/nemo-pathbar.c
- src/nemo-window.c
A few still remain, but this should make logs readable again.
Edit: I haven't tracked down the NemoWindow warnings yet and the NemoWindowPane warnings are fixed by this gtk commit https://github.com/GNOME/gtk/commit/ddcf47026dbbe58dca3b34c7bb1ec63bb50a861
Fixes #1153
> Silence a bunch of allocation warnings when using GTK 3.20

- libnemo-private/nemo-file-operations.c
Currently it was 15 seconds, which is a little too much. Most
of the time 8 seconds is enough, and even more with SSDs. In this
way we are able to provide feedback of the remaining time to the
user in a more reasonable time.
https://github.com/GNOME/nautilus/commit/7d40ce7f94390a646c54273225fc1cd08aa9ccec
> file-operations: reduce the time for reliable transfer rate

- src/nemo-convert-metadata.c
- src/nemo-main.c
removes some of the distracting build warnings
> remove deprecated and no longer necessary g_type_init

- src/nemo-icon-view.c
This is needed with gtk+-3.20 as view on
.nemo-window .nemo-window-pane > notebook box.vertical > overlay > scrolledwindow > widget.view {}
does not work, it is impossible to set a bg color.
In result you can only set the bg color with 
.nemo-window .nemo-window-pane > notebook box.vertical > overlay > scrolledwindow {}
, but than you have the wrong bg color for scrollbar junctions ( the little square beside srollbars) in nemo treeview.
This gtk+ bug affect all file-browsers (caja, nemo and nautilus), but you see that only if you don't use overlay-scrollbars.
A more detailed description you will find here.
https://github.com/mate-desktop/caja/commit/e5c29655e5301b6d4ba19a3d4970745804039c0e
With setting the view style class on the scrolledwindow we can use this setting in themes
(gtk+-3.20 …
> add view style class on icon view scrolled window

- src/nemo-view.c
Avoid leaving zombie processes.
This fixes the debian bug http://bugs.debian.org/825757
> Close open_as_root child on child exit

- src/nemo-application.c
Fix for https://github.com/linuxmint/nemo/issues/569
based on
https://github.com/lukefromdc/caja/commit/9fb12116c1a09221a88f5c1a7e9010022c96df66
This fixes a GApplication command line issue inherited from Nautilus 3.4. The issue is that using --geometry in a second invocation of nemo sets self->priv->geometry in the local instance, but the windows are opened by the remote (already running) instance. That reads it's own version of self->priv->geometry, which is not written to by setting the same variable in the local instance. There are very few ways to pass data from a local command line to "open" but Gapplication provides the "hint" string variable. It can pass the geometry string, which can then be written to self->priv->geometry, making the geometry option work again.
> Fix --geometry option when Nemo is already running

- Makefile.am
- autogen.sh
- configure.ac
- cut-n-paste-code/libegg/Makefile.am
- debian/rules
- eel/Makefile.am
- libnemo-extension/Makefile.am
- libnemo-private/Makefile.am
- src/Makefile.am
- test/Makefile.am
gnome-common is deprecating some vars and macros, listed here:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=829932
This change follows the gnome recommendations from:
https://wiki.gnome.org/Projects/GnomeCommon/Migration
> Migrate away from gnome-common deprecated vars and macros

- src/nemo-file-management-properties.glade
https://github.com/linuxmint/nemo/commit/70753fac0eb1483ad828ed78a5401a3834bcc4c7#diff-0db86c32c4fbff82c6f9e6f2571fbe10 removed the "Show text in icons" preference but also removed a bit too much from the glade file. Set the border width back to 0 so the dialog looks correct again
> nemo-file-management-properties: Fix an accidental removal

- libnemo-private/nemo-clipboard-monitor.c
- libnemo-private/nemo-clipboard.c
- libnemo-private/nemo-directory-async.c
- libnemo-private/nemo-dnd.c
- libnemo-private/nemo-icon-dnd.c
- libnemo-private/nemo-tree-view-drag-dest.c
- src/nemo-convert-metadata.c
- src/nemo-desktop-item-properties.c
- src/nemo-image-properties-page.c
- src/nemo-location-bar.c
- src/nemo-pathbar.c
- src/nemo-places-sidebar.c
- src/nemo-properties-window.c
- src/nemo-view.c
based on 
https://git.gnome.org/browse/nautilus/patch/libnautilus-private/nautilus-directory-async.c?id=c00eb306ee711632072f761bfa4e814c405a82d2
> Fix GCC pointer signedness warnings

- po/README
Because it took me way too long to find the translation site on Launchpad.
> Add link to Launchpad translations to README

- src/nemo-list-view.c
It shinks all non "name" columns to an unreadable size.
It adds also log spam and suffers a compiler warning because of a missing
"static void". Tested on Ubuntu Trusty.
> Remove conditional ellipsis code for GTK < 3.12.0 builds.

- src/nemo-application.c
This commit fixes the maximized window state not being preserved properly since #1268 and the followup commit.  While trying to track this down, I found that we are in some cases passing NULL to g_application_open in the hint parameter which is explicitly forbidden and results in unexpected strings being passed to nemo_application_open. I have added a NULL check there to prevent this.
Aside from that, I also had to add a check for an empty string in open_window otherwise we override the previously restored window state in too many cases.
> nemo-application.c: fix maximized window state preservation

- src/nemo-window.c
As pointed out in #1096, the sidebar width setting is written an excessive
amount of times during a resize operation. Instead of using a likely
immediate callback with g_idle_add, use g_timeout_add with a 100ms interval.
The timeout is removed and re-added every time the sidebar width changes,
so the callback will not fire until 100ms after the last change.
This setting may still be written multiple times during a single resize
operation.
Fixes #1096
> nemo-window.c: save sidebar width 100ms after last change

- libnemo-private/nemo-global-preferences.h
- libnemo-private/org.nemo.gschema.xml.in
- nemo.pot
- src/nemo-file-management-properties.c
- src/nemo-file-management-properties.glade
- src/nemo-icon-view.c
I am used to double left click on blank area to go to parent folder on my working computer under MS Windows with QTTabBar (extension of MS Explorer to have tab and useful shortcuts).
So as I started to use Nemo with Cinnamon under ArchLinux, i was expected to found something similar so I propose this patch with an option to not change standard behavior.
> Add option about mouse double click to go to parent folder

- src/nemo-main.c
based on 94dcf03e5bc9cd1db83cf3016289e305e13694d4
From 94dcf03e5bc9cd1db83cf3016289e305e13694d4 Mon Sep 17 00:00:00 2001
From: Florian <fmuellner@gnome.org>
Date: Wed, 7 Dec 2016 17:11:56 +0100
Subject: desktop: Force X11 backend
At least for the time being, desktop icons are not supported on
wayland. This may or may not change, but in the meantime we can
still meet user expectations by forcing the supported backend
instead of failing with an unsupported one.
https://bugzilla.gnome.org/show_bug.cgi?id=748347
Fixes https://github.com/linuxmint/nemo/issues/1343
> Force X11 backend

- libnemo-private/nemo-file-operations.c
Based on https://git.gnome.org/browse/nautilus/commit/?id=d4a4f7915ccad4fbe9bb726dd9f876738c7960d4
From d4a4f7915ccad4fbe9bb726dd9f876738c7960d4 Mon Sep 17 00:00:00 2001
From: Carlos Soriano <csoriano@gnome.org>
Date: Thu, 24 Nov 2016 13:32:02 +0100
Subject: file-operations: don't recurse for trash operations
We were scanning the sources as we do for copy and move operations,
and to count the files we were recursing inside directories.
However, the trash operation doesn't recurse at all, so the operation
progress was wrong.
Instead of that, don't recurse for counting the number of files, so the
trash progress is correct. Although is not coherent with the rest of the
operations, recursing for just showing all the files in the progress
would be extremely counterproductive. …
> file-operations: don't recurse for trash operations

- src/nemo-window-manage-views.c
This prevents the pending selection from getting stepped on by
another reload request.
https://bugzilla.gnome.org/show_bug.cgi?id=608831
> Don't reload while a reload is ongoing

- libnemo-private/nemo-file-operations.c
- src/nemo-view.c
Bail out early if there is no selection and and add a bit of extra protection
in case we are inadvertently doing this elsewhere.
Closes: https://github.com/linuxmint/nemo/issues/1415
> Fix a crash when attempting to delete an empty selection on the desktop

- src/nemo-thumbnail-problem-bar.c
- src/nemo-view.c
- src/nemo-window-manage-views.c
- src/nemo-window-menus.c
- src/nemo-window-slot.c
- src/nemo-window-slot.h
- src/nemo-window.c
commit https://github.com/linuxmint/nemo/commit/c4af24245408eb44cd019d9bcbf6131d9b146328
prevented the search from ever resolving. This commit is a follow up to the
original nautilus commit that fixes the issue.
Based on https://github.com/GNOME/nautilus/commit/eccc2046979be5a8073376f4611e0aa7ca89bc4a
> Fix search never resolving

- data/dbus-interfaces.xml
- libnemo-private/nemo-dbus-manager.c
Add MoveURIs, which has the same signature as the existing CopyURIs
method.
Motivation: Better integration with other applications.
Why should a launcher/command shell integrate with nemo? The user gets a more consistent experience, progress, conflict resolution and error handling are all handled by nemo in a familiar interface. The nemo plugin in kupfer is available in its latest version. It can already handle other neat operations that nemo provides:
> nemo-dbus-manager.c: Add MoveURIs method

- autogen.sh
Based on https://git.gnome.org/browse/nautilus/commit/autogen.sh?id=753e9d812cc33b5477418152abaa03795b9059c8
autoreconf takes care of running aclocal and other commands in the right order.
> autogen.sh: don't run aclocal

- configure.ac
Based on https://git.gnome.org/browse/nautilus/patch/configure.ac?id=450bf6bc9371d246f3084757efaef1a663d9f416
> Make libselinux dependency controllable by configure switch

- debian/rules
Disable selinux for Debian rules or you could add libselinux-dev to the build deps.
> Disable selinux for Debian rules

- libnemo-private/nemo-file-operations.c
The current string format causes problems when localized to certain languages
that need to rearrange the structure. Since a placeholder name is not strictly
necessary with template files, just remove it.
Fixes #1278
> nemo-file-operations.c: use only template filename for new files

- src/nemo-application.c
- src/nemo-desktop-window.c
- src/nemo-window.c
- src/nemo-window.h
So we can use Gtk features with it.
Note that we set show_menubar always to FALSE, since we already show a
menubar ourselves.
Nautilus Commit: 581a1df69a19d7ac7236202ca2a1839e667bce88
> window: make NemoWindow a GtkApplicationWindow

- src/nemo-location-bar.c
- src/nemo-window-pane.c
Avoids GFile->URI->GFile roundtrips
This is adopted nautilus patch: 
ce16451d1d7f384ca296ca7ce824938606b21af0
> location-bar: use a GFile in location-changed signal

- makepot
- polkit.its
- polkit.loc
- src/org.nemo.root.policy.in
See https://github.com/linuxmint/mintsources/issues/75
I changed the `<vendor>` from "Linux Mint" to "Nemo Project" because Nemo isn't specific to the Linux Mint distros.
> Updated pkexec support

- libnemo-private/nemo-column-utilities.c
- libnemo-private/nemo-file.c
- libnemo-private/nemo-file.h
- libnemo-private/nemo-global-preferences.c
- libnemo-private/nemo-global-preferences.h
- src/nemo-file-management-properties.c
- src/nemo-properties-window.c
This is a rebase of the recent changes of the Modified column from Nautilus. 
It replaces the broken width dependent formating with a compact and human readable format. 
Depending on the age of the file, it displays: 
- 14:58 
- Yesterday
- Monday
- 2 February
- 10 Aug 2016
For photo folders or similar, there is a new right aligned "Modified - Time"  column available, which adds always the time to the above formats. 
The time format follows the org.cinnamon.desktop.interface settings. 
Unlike in Nautilus, the alternative preference option for full date and iso date is kept. 
This PR fixes also a Bug in the calculation of "today", which was introduced by 
744f164af91ccb85a5af2289634303884223fea3
reported here https://github.com/daschuer/nemo/issues/1
> Better format for the Modified coloumn + Today bugfix 

- data/nemo.desktop.in.in
```
+ desktop-file-validate /home/leigh/development/rpmbuild/BUILDROOT/nemo-3.4.0-0.0.20170426git5a50a78.fc26.x86_64/usr/share/applications/nemo-autorun-software.desktop /home/leigh/development/rpmbuild/BUILDROOT/nemo-3.4.0-0.0.20170426git5a50a78.fc26.x86_64/usr/share/applications/nemo-autostart.desktop /home/leigh/development/rpmbuild/BUILDROOT/nemo-3.4.0-0.0.20170426git5a50a78.fc26.x86_64/usr/share/applications/nemo.desktop
/home/leigh/development/rpmbuild/BUILDROOT/nemo-3.4.0-0.0.20170426git5a50a78.fc26.x86_64/usr/share/applications/nemo.desktop: error: file contains key "Comment" in group "Desktop Action open-home", but keys extending the format should start with "X-"
/home/leigh/development/rpmbuild/BUILDROOT/nemo-3.4.0-0.0.20170426git5a50a78.fc26.x86_64/usr/share/applications/nemo.de …
```
> fix desktop file error

- src/nemo-navigation-action.c
This pull request contains additions discussed in my last PR #1475.
It extends the Toolbar-Button event handling: CTRL-Clicking also opens new tabs.
While testing, I observed, that opening "Back" and "Forward" in a new tab went to the second element in the history. This PR fixes this also.
Thanks for merging my last pull request.
> nemo-navigation-action.c: Extend, Fix Middle-Click

- src/nemo-places-sidebar.c
The current icon leaves us with a dark icon on the dark background. It doesn't
look good and using an actual folder fits in better with the rest of the
sidebar items.
> nemo-places-sidebar: Use folder-recents for the recent icon

- src/nemo-icon-view-container.c
- src/nemo-icon-view-grid-container.c
Update grid auto arrange icon order. More user friendly due to rubbish bin remaining in the same position, and mirrors the behaviour of other popular OS such as Windows
> Nemo modify desktop icon order

- eel/eel-glib-extensions.c
May improve performance somewhat for very high volume file copies
though I have no way to test with the volumes reported here https://bugs.launchpad.net/linuxmint/+bug/1663186
> eel_g_list_str_copy: replace contents with g_list_copy_deep

- eel/eel-editable-label.h
move fields in a structure to avoid memory padding
made padding explicit to avoid warning messages if the padding
compiler warnings are on
> eel-editable-label.h: Avoid memory padding

- data/mount-archive.nemo_action.in
As supported within limits of libarchive, which gvfsd-archive relies on.
More info: https://github.com/libarchive/libarchive/wiki/LibarchiveFormats
> Add .rar and .7z to archive mounting action

- src/nemo-view.c
I found it annoying that after I double-clicked a desktop icon to launch a program, it stayed highlighted.  This change fixes that for files on the desktop only.  Files in nemo windows will still stay selected after activation.  This mirrors the behavior on MS Windows 10 (and possibly earlier versions, but I don't have them right now to test with).
> When activating files on desktop (only), deselect them after activating them

- src/nemo-window.c
This also fixes the trash bar resizing the left pane. I used printf to check the value of the `w` variable, and it was always logging 0 in `create_extra_pane`. Deferring the repositioning seems to correct this.
Closes #1180
> Fix left pane in dual pane mode reverting to minimum width

- src/nemo-bookmarks-window.c
> nemo-bookmarks-window: rename some shadowed variables

- src/nemo-file-management-properties.c
and treat a couple of other compiler warnings
> nemo-file-management-properties: rename shadow variable

- libnemo-private/nemo-desktop-metadata.c
and a const assignment warning
> nemo-desktop-metadata correct wrong type of variable passed as parameter

- src/nemo-properties-window.c
It appears to be a bit faster.  https://github.com/GNOME/nautilus/commit/2b6ca358c5187c3ef741ce29dc134db1b395f4fd
> nemo-properties-window: use gdk_pixbuf_scale_simple ()

- eel/eel-vfs-extensions.c
https://github.com/GNOME/nautilus/commit/0b6a05851d753c48197045079cc6e43237fc0b8b
ensures that if we duplicate thing.tar.bz  we get thing (copy).tar.bz rather than
thing.tar (copy).bz  etc.
> eel-vfs-extensions: update filename extensions

- libnemo-private/nemo-global-preferences.h
- src/nemo-view.c
- src/nemo-window-menus.c
Just a small fix.
Nemo ignores exec-arg in org.cinnamon.desktop.default-applications.terminal the using "open in terminal".
I fixed this because i thought i could stop using a wrapper script to open a new tab in guake. Sadly didn't fix my problem.
But as i put a litle effort into the patch, i wanted to share it :)
Hopefully someone have a use for it.
> Use exec-arg when "open in terminal"

- debian/nemo.install
- debian/rules
- meson.build
--libexecdir=/usr/libexec option isn't respected and installs files to  /usr/lib64/nemo/
```
/usr/lib64/nemo/nemo-convert-metadata
/usr/lib64/nemo/nemo-extensions-list
```
libexecdir isn't the same as libdir and hard coding nemo isn't acceptable as I want to install in
```
/usr/libexec/nemo-convert-metadata
/usr/libexec/nemo-extensions-list
```
>  Make the libExecPath usable 

- libnemo-private/org.nemo.gschema.xml
After update Nemo, I cannot run 'open as root' folder action (menu) because missing gsettings key 'show-root-warning'
> fix open as root error

- src/nemo-properties-window.c
These are long deprecated and leave you with some ugly icons on the buttons.
> nemo-properties-window: Stop using stock buttons

- libnemo-private/nemo-icon-info.h
The order of `gsize max_height` & `gsize max_width` in .c file is different from the header file.
> Fix function argument order

- libnemo-private/meson.build
This is not meant for public use, hence why it is a static-only library
linked directly into nemo. During the meson port it was accidentally set
to be installed, where the autotools build marked it as noinst.
> meson: don't install libnemo-private.a

- src/nemo-query-editor.c
It seems that details was replaced with priv all over the file, including the license paragraph.
> Revert license tweak done by db6414a

- data/nemo.desktop.in
- generate_additional_file
Some distributions change the name from "Files" to "Nemo", making harder finding this by "file".
> Add some keywords to the desktop entry

- libnemo-private/nemo-icon-dnd.c
- libnemo-private/nemo-tree-view-drag-dest.c
This fixes #407. I verified that this enables dragging images from Firefox Nightly to this build of nemo.
> Prefer XDS Protocol Type over _NETSCAPE_URL to make DnD work in Firefox.

- gresources/nemo-desktop-overlay.glade
- src/nemo-desktop-overlay.c
- src/nemo-extension-config-widget.c
It was showing a URL for the desktop settings link's tooltip, and
we're not actually using any URLs for these.
> desktop/extension config: remove incorrect tooltips

- gresources/nemo-file-management-properties.glade
- libnemo-private/nemo-file-operations.c
- libnemo-private/nemo-global-preferences.h
- libnemo-private/org.nemo.gschema.xml
- src/nemo-file-management-properties.c
First of all, thanks for the Linux Mint 19.1/Nemo 4.0.6 release.
I just switched over from Win10 to Mint Cinnamon, and find that I also missed the "Move to Trash" confirmation (like the others did in #1135).
So this is my attempt to implement the Move to Trash confirmation dialog: 
(which is largely a replicate of the confirm delete dialog)
It's configurable with the first option under Trash in Preferences (default to off): 
> Confirm before moving files to the Trash
While implementing the Move to Trash confirmation dialog above, I came across the following stanza in [GNOME HIG](
https://developer.gnome.org/hig/stable/dialogs.html.en):
> **Default action and escape**
> Assign the return key to activate the primary affirmative button in a dialog (for example Print in a print dialog). This …
> Add Move to Trash confirmation option

- src/nemo-window-manage-views.c
With this change, the warning about the problems with the thumbnail cache is only shown when thumbnails are enabled.
Usually, I set my thumbnail cache to read-only to prevent new thumbnails from being generated (due to privacy concerns). Dismissing the warning during every boot gets a bit tiring... :wink:
> Don't warn about thumbnail cache problems when thumbnails are disabled

- gresources/nemo-file-management-properties.glade
- libnemo-private/nemo-directory.c
- libnemo-private/nemo-file.c
- libnemo-private/nemo-global-preferences.c
- libnemo-private/nemo-global-preferences.h
- libnemo-private/org.nemo.gschema.xml
- src/nemo-file-management-properties.c
- src/nemo-toolbar.c
- src/nemo-view.c
- src/nemo-window-manage-views.c
- src/nemo-window-menus.c
- src/nemo-window.c
This adds settings to inherit the view type and thumbnailing setting from a parent.
If used, folders inherit those settings from their parent, if said folder does not have an own setting for it.
The per-folder-thumbnailing is reimplemented to respect the ignore-metadata setting.
This also fixes resetting the view.
> Settings inheritance for thumbnailing and view type - Take 2

- gresources/nemo-style-application.css
Closes https://github.com/linuxmint/nemo/issues/2121
> Nemo desktop entry - ensure caret-color matches text color

- libnemo-private/nemo-mime-application-chooser.c
The creation of the label "Select an application in the list to open [...]" in the "Open With" file properties tab fails because of file names which include HTML special chars like ampersand or angle brackets.
I wasn't able to inject HTML into the label because of forbidden slashes in file names. HTML comments (``) do work though!
Replaced `g_strdup_printf` with `g_markup_printf_escaped` to fix that.
> nemo-mime-application-chooser.c: escape file names in Open With tab

- src/nemo-view.c
A small fix so that the `DirViewActions/OpenInTerminal` shortcut also opens a Terminal if a file is selected. It then uses the parent directory as working directory.
> Open Terminal in parent directory if a file is selected

- files/usr/share/nemo/actions/sample.nemo_action
- libnemo-private/nemo-action.c
The idea is to make it possible for an action to specify a condition which runs a command.
Say we want a "Set as wallpaper" action but only for pictures which dimensions are more than 1000x1000px. We can write a /usr/bin/check-picture-is-big program which calculates the dimensions of the selected picture and returns 0 if it's 1000x1000px or more, or 1 otherwise.
This PR adds the ability for the action to specify:
`Conditions=exec /usr/bin/check-picture-is-big %f`
TODO:
> [WIP] Nemo actions: Add support for exec condition

- meson.build
Based on https://github.com/GNOME/nautilus/commit/7605b17b2757fa3331f2551c04208e833cd723e1#diff-969b60ad3d206fd45c208e266ccfed38
Buildlog before
https://kojipkgs.fedoraproject.org//packages/nemo/4.4.1/2.fc32/data/logs/x86_64/build.log
Buildlog after
https://kojipkgs.fedoraproject.org//packages/nemo/4.4.1/3.fc32/data/logs/x86_64/build.log
> meson.build: Disable GLib deprecation warnings

- libnemo-private/nemo-file-operations.c
Fixes https://github.com/linuxmint/mint19.3-beta/issues/40 and https://github.com/linuxmint/nemo/issues/1814 and https://github.com/linuxmint/nemo/issues/1935
Based on https://gitlab.gnome.org/GNOME/nautilus/commit/0dfb6dec99c166cd35d9d87da82653f93365b227
> file-operations: fix copying from the trash

- eel/eel-editable-label.c
- libnemo-private/nemo-icon-canvas-item.c
Fixes for https://github.com/linuxmint/nemo/issues/2214
Pango 1.44 got the ability to automatically hyphenate on line breaks,
which is on by default, but can be set off by a new attribute.
As a result, we now hyphenate filenames, which is confusing, because
a filename may already include hyphens.
To restore the previous behavior, let's not insert hyphens when
breaking filenames in multiple lines.
Based on https://github.com/mate-desktop/caja/commit/b50e36b639aca25c8bf3d21dc1547fc6f7a6f442
> Don't hyphenate long filenames

- libnemo-private/nemo-global-preferences.c
- libnemo-private/nemo-global-preferences.h
Fixes https://github.com/linuxmint/nemo/issues/2305
Based on https://gitlab.gnome.org/GNOME/nautilus/commit/96554c2020b19c11eb065b24c9fc5457626c8bc2
> nemo-global-preferences: use 'extern' properly

- libnemo-extension/meson.build
We use the typelibdir variable provided in gobject-introspection.pc
typelibdir=${libdir}/girepository-1.0
and replace $(libdir) with that of this project.
> build: use define_variable for typelib directory

- src/nemo-view.c
Hi,
Default application is filtered out from the "Open with" menu for all files.
The default application must show up in the "Open with" menu, if the default action for the file(s) is not opening with the default application, but, for example, launch of the file(s) with execution permission.
This pull request addresses the issue described above.
**The change requires testing. I didn't build and test it myself.**
Cheers!
> Show default app in "Open with" menu

- src/nemo-notebook.c
This way we don't end up with labels that show only three dots when you have
a few open tabs.
> nemo-notebook: Add a minimum width for the tab labels

- files/usr/share/nemo/actions/sample.nemo_action
- libnemo-private/nemo-action.c
- libnemo-private/nemo-action.h
The new modifier will return the file name with the extension stripped.
This allows us to create actions such as "Extract \<archive.ext\> to \<archive\>..." to avoid a situation where common "Extract here" actions would otherwise dump contents of the archive to the current directory if it does not contain a root directory inside while being quicker to use than "Extract to" actions, for example:
```[Nemo Action]
Active=true
Name=Extract to %e...
Comment=Extract "%f" to "%e"
Exec=file-roller --extract-to=%P/%e %F
Icon-Name=gnome-mime-application-x-compress
Selection=notnone
Extensions=zip;7z;ar;cbz;cpio;exe;iso;jar;tar;tar.Z;tar.bz2;tar.gz;tar.lz;tar.lzma;tar.xz;
Quote=double
```
> Add %e action token (extension stripped filename)

- libnemo-private/nemo-directory-async.c
- libnemo-private/nemo-directory-private.h
- libnemo-private/nemo-directory.c
- libnemo-private/nemo-file.c
Note: This patch is an untested port on the original Nautilus patch. 
Gio now parses .hidden files itself and sets the hidden flags in
the GFileInfo, so no need to do it again.
We already rely on the glib version that has this support added.
See issue: https://github.com/linuxmint/nemo/issues/206
> Remove .hidden file code now that gio does if for us

- libnemo-private/org.nemo.gschema.xml
The current setting of 148 causes text like "Downloads" to be ellipsized by
default. Up the size some to prevent this.
> settings: Set the default width of the sidebar to 170

- libnemo-private/meson.build
- libnemo-private/nemo-search-engine-tracker.c
- libnemo-private/nemo-search-engine-tracker.h
- libnemo-private/nemo-search-engine.c
- meson.build
- meson_options.txt
This PR reverts 5db7a44e8086d1b77f6384b272353c932404a05a and applies a patch to add support for `tracker-2` taken from #2065 
There is really no reason to drop support for this when there is a patch that applies cleanly and keeps  it usable with current versions of tracker.
> Add tracker support

- data/nemo.desktop.in
- generate_additional_file
Replace icon "folder" with "system-file-manager". Issue #1686 discussed
already, that it should not use "folder" to follow free desktop
standards, and it was changed to "nemo" in 5d4ca0 ("Rename Nemo icon
from places to nemo"). It looks like it was changed back by accident in
099421 ("l10n: Update POT file and generate files").
Change it to "system-file-manager", because that makes it pick up a nice
icon with the default GNOME theme. Adjust "generate_additional_file"
too, so it won't get overwritten by a accident again.
> data/nemo.desktop.in: fix icon

- debian/menu
From Pino Toscano patch for debian packages.
Drop Debian menu file (wrongly installed in gir1.2-nemo-3.0) since nemo already
provides a .desktop file.
> Drop Debian menu file

- src/nemo-pathbar.c
There is a section that was originally a copy of up_slider_button and one line wasn't changed to down_slider_button.
> Fixed small copy-paste bug.

- src/nemo-pathbar.c
In nemo-pathbar.c in the `nemo_path_bar_get_preferred_width` function there is a height and a child_height variable that are set but never used. The commit removes those unused variables.
> Removed unused variables in pathbar function

- libnemo-private/nemo-file.c
Fixes #2546
Introduced in 99102d4 as a design improvement.
This also fixes that you can copy the datetime string from a file's properties window intro other programs as a datetime string (e.g. python shell).
> Remove uft8 colon-like char in datetime strings

- libnemo-private/nemo-action.c
This PR resolves #2513 
Skip escaping the quotes when the nemo action is using the Quote=double
> Fix for #2513. Avoid single quote escape

- debian/control
- meson.build
Patch of Norbert Preining from debian packages.
With this check pango even if the version is lower that 1.44 (for example for
buster).
Added missed libpango1.0-dev in debian/control build-deps.
Note: I suppose Norbert set pango >=1.42 because is a version tested but probably an older version is supported, for example before meson port in configure.ac the min pango version required was 1.28.3, someone can confirm it or if a newer version is really required please?
> make sure pango development files are installed

- eel/eel-gnome-extensions.c
This PR resolves #2499 
There still needs to be a change to setting the default exec-arg from "-x" to "--" in the case of gnome-terminal. But this PR will at least fix the issue if a user does not have a exec-arg setting in place.
> Fixes #2499. Changes the option from -x to -- when using gnome-terminal

- src/nemo-connect-server-dialog.c
This PR resolves #2359 
Removed the Help button. Will add back once a site with documentation has been established.
> Fixes issue 2359. Removes Help button

- src/nemo-mime-actions.c
This PR resolves #2442 
Added check for URI being null, which was a result when `nemo_file_get_uri` failed. Displays a simple message dialog to the user informing them an error occurred and avoids the previous problem of a segfault.
> nemo-mime-actions.c: Don't show mime button if the activation URI is null

- files/usr/share/nemo/actions/sample.nemo_action
- libnemo-private/nemo-action.c
- libnemo-private/nemo-action.h
I ran into a situation where a tool I was trying to call as an action also uses `%` tokens in its format string. Nemo stops processing tokens if it hits one it doesn't know about, so there was no way to run this tool directly. I considered just making it ignore unknown token types, but decided it would be better to add `%%` to insert a literal `%` in the command, since you might need to pass one that _is_ a valid action token.
> Add escaping for percent sign in action Exec

- libnemo-extension/meson.build
Without this commit, a build configured with --prefix=/usr and
--libdir=/usr/lib will generate typelibdir = "//lib/girepository-1.0",
which isn't correct.
> build: fix typelibdir in libnemo-extension/meson.build.

- gresources/nemo-file-management-properties.glade
- libnemo-private/nemo-file.c
- libnemo-private/nemo-file.h
- libnemo-private/nemo-global-preferences.h
- libnemo-private/org.nemo.gschema.xml
- src/nemo-file-management-properties.c
- src/nemo-icon-view-container.c
- src/nemo-icon-view.c
- src/nemo-list-model.c
- src/nemo-list-model.h
- src/nemo-list-view.c
- src/nemo-tree-sidebar.c
- src/nemo-view.c
- src/nemo-view.h
Took a crack at implementing an option to toggle sorting favourites before other files, as requested in #2624. 
Changes are based off of the existing "sort folders before files" option and use a new gsettings key:
`gsettings set org.nemo.preferences sort-favorites-first (true|false)`
Demo:
> Added option to toggle sorting favorites before other files

- libnemo-private/nemo-file.c
With some GIO backends (observed at least with sftp),
g_file_info_get_symlink_target() returns an empty string rather
than NULL for non-symlinks. A warning and then segfault result:
** (nemo:8386): WARNING **: 18:34:22.807: File has symlink target, but  is not marked as symlink
Thread 1 "nemo" received signal SIGSEGV, Segmentation fault.
0x00007ffff71beac0 in g_str_hash () from /usr/lib/libglib-2.0.so.0
(gdb) bt
#0  0x00007ffff71beac0 in g_str_hash () at /usr/lib/libglib-2.0.so.0
#1  0x00007ffff71bfa2f in g_hash_table_lookup_extended () at /usr/lib/libglib-2.0.so.0
#2  0x000055555564926e in modify_link_hash_table at ../libnemo-private/nemo-file.c:600
#3  0x000055555564ed11 in add_to_link_hash_table at ../libnemo-private/nemo-file.c:642
#4  update_info_internal at …
> Fix segfault when g_file_info_get_symlink_target() returns "".

- src/nemo-main-application.c
This implements the feature request https://github.com/linuxmint/nemo/issues/2674.
I implemented it by sending the `EXISTING_WINDOW` in the `options` variable to the `nemo_main_application_open()` function.
The function itself that opens new tabs is `open_tabs_in_existing_window()`, which finds an active instance of a Nemo window and opens new tabs there.
> Added an `--existing-window` flag to open URLs in an existing window

- src/nemo-desktop-icon-grid-view.c
- src/nemo-desktop-icon-view.c
- src/nemo-icon-view.c
- src/nemo-list-view.c
- src/nemo-view.c
- src/nemo-view.h
- src/nemo-window-menus.c
Previously, the menu was updated when the selection changed, during
loading of the view, when a file in the view (or the view location
itself) changed and many other events. This would end up causing
a lot of unnecessary updates, which could have a noticeable impact
on performance.
Instead, only flag the menu as needing an update when any of these
events occurs, and only actually update the menu just before showing
it.
ref: #2718
> nemo-view.c: Only update the context menu when it's about to be shown.

- docs/nemo.1
Added the new flag to the docs. I think `docs/nemo.1` is the only place where docs live. Correct me if I need to add it in more places.
> docs: added docs for the `--existing-window` flag

- libnemo-private/nemo-global-preferences.h
- libnemo-private/org.nemo.gschema.xml
- src/nemo-mime-actions.c
Allow images to be viewed in supported image viewers in the same order as they are shown in the current nemo view (directory or search).
For example:
- If images are sorted in ascending date order, opening an image and pressing next/previous in the image view will go to the next/previous image chronologically.
- If the image is part of a search result, available images in the image viewer are limited to the other search results.
This is similar to how images are handled in Windows Explorer and Windows Photo Viewer, which I find so intuitive a feature, I didn't even think of it as one until moving to Linux on my personal machine.
So this is an implementation that seeks to address this in a way that doesn't require specific coupling between applications, or extensive changes to image …
> Nemo view order in supported image viewers

- src/nemo-window.c
The menu bar seems to lose focus after a sub-menu appears. As a workaround, one may check whether some element is selected before hiding it.
I added also some more code (I am no C programmer, this part can be improved for sure) to hide the menu immediately after choosing an option, otherwise there is still a small delay and the experience feels weird.
~~**Remark**: on a touchscreen, you can't keep your finger pressed against the options and then release to select, so if you do not hit the proper option on your first try, then the menu also closes. This is sub-optimal.~~
~~**Remark 2**: this also seems to happen with a mouse.~~
> Fix #2347 - Nemo menu unaccessible after hiding it

- src/nemo-list-view.c
This was done for the icon view some time (305caebc61943be64) but
not the list view.
This feature is still quite limited, as the double-click must occur
in an empty row, not just a blank area in the view (this would
break row selection, which isn't an option).
Ref: #1516
> nemo-list-view.c: Implement 'double-click blank area to go up one folder' on the list view.

- docs/nemo.1
- src/nemo-main-application.c
This PR resolves #2415. Removed the ability to run nemo self-checks. Removed option from nemo man page.
If anything needs to be fixed, changed, or removed, just let me know and I'll make the changes accordingly. Thanks.
> Remove self-check functionality

- files/usr/share/nemo/search-helpers/ps2ascii.nemo_search_helper
Specifically, there is no such thing as ps2txt and AFAICT never has been. But debian has for some decades been providing a convenience symlink from ps2ascii so that you can invoke it as 'ps2txt' as well, resulting in much confusion from people who actually try to do so, start relying on doing so, and then get bug reports for their software from other distros where this just plain does not work.
> make ps2txt search helper work on non-debianlike distros

- src/nemo-toolbar.c
Quite a few years ago we changed to using the raised button style that was
popular at the time. Now some themes are going out of our their way to get
rid of that style. So just go back to using the flatter style.
> nemo-toolbar.c: Use flat button style

- src/nemo-window-menus.c
> Issue 2809. Cleans up ToolTip for Search

- libnemo-private/nemo-file-conflict-dialog.c
- libnemo-private/nemo-file-conflict-dialog.h
- libnemo-private/nemo-file-operations.c
This feature appears in the GUI as a new button "Autorename" added to all the different conflict dialogs
This uses the already implemented "unique name" policy that allows copying/moving a file/folder with the same name than another in destination folder by renaming it automatically in this fashion:
"example file (copy).txt" "example file (another copy).txt" "example file (3rd copy).txt" etc.
The main interest of this new feature is its cumulation with the "apply to all" checkbox, allowing automatic renaming for all conflicts.
No bug were found upon testing all relevant use cases
Only the functioning feature was implemented. Translation is left to the maintainers / other contributors.
This addition is originally intended to be merged to the maintenance branch of the 4.4 version, as it was …
> Added new "Keep both files" conflict handling option

- debian/control
- meson.build
- src/meson.build
- src/nemo-application.c
- src/nemo-desktop-application.c
- src/nemo-main-application.c
- src/nemo-places-sidebar.c
- src/nemo-progress-ui-handler.c
Replace libnotify with gio's GNotification and thus remove a dependency.
Fixes: #2931
I tested the unmount pending/done notifications, but didn't manage to get the "All file operations have been successfully completed" notification though. Wasn't able to trigger that one somehow.
> Port to GNotification

- src/nemo-window-menus.c
- src/nemo-window.c
Fixes #2921.
Some action callbacks are already guarded with !NEMO_IS_DESKTOP_WINDOW() checks, but not enough unfortunately.  Guards are added to these callbacks for the following justifications:
- CTRL+Q: action_close_all_windows_callback (segfaults)
- CTRL+L: action_menu_edit_location_callback (does nothing but print nonfatal assertion failures)
- CTRL+D: action_add_bookmark_callback (adds bogus bookmark)
- CTRL+B: action_edit_bookmarks_callback (crashes nemo-desktop with fatal assertion failure)
- ALT+P: action_plugins_callback (fails to load extensions)
- F9: action_show_hide_sidebar_callback/nemo_window_get_sidebar_id (silently changes global sidebar preference even though desktop has no sidebar)
- / or ~: nemo_window_prompt_for_location (does nothing but print nonfatal assertion …
> Add !NEMO_IS_DESKTOP_WINDOW() guards to callbacks

- libnemo-private/nemo-file-operations.c
Fixes:  https://github.com/linuxmint/nemo/issues/2708
> Add native exfat renaming support

- gresources/nemo-file-management-properties.glade
- libnemo-private/nemo-global-preferences.h
- libnemo-private/org.nemo.gschema.xml
- src/nemo-file-management-properties.c
- src/nemo-window-manage-views.c
Reasons to add this option: I don't need that functionality, it is wasted cycles and it takes too much space away from the file list.
I added the option in the media handling section, although it is a nemo specific option but is very much a media handling option, is it ok?
> Add option to disable or enable content type detection of mounted media.

- libnemo-private/nemo-icon-container.c
The details pointer was freed before g_list_free was called on
details->current_section. Freeing details also got rid of it, so
swap the order so both are freed in proper order.
Fixes https://bugs.launchpad.net/ubuntu/+source/nemo/+bug/1945903
---
I do not know what caused this bug for the user in the first place. It looked like he was DE hopping; I even applied the Breeze theme which was shown in some warnings but still couldn't reproduce it. If anything this'd be stability fix
> icon-container: Don't free a pointer after it has already been freed

- eel/eel-string.c
- eel/eel-string.h
I checked the GLib source code for `g_shell_parse_argv` and noticed that in addition to quotes, spaces, tabs, newlines and backslashes, number signs are also specially handled. They will truncate the Exec command line when handling paths that contain a space followed by a number sign. Thus number signs in paths also need escaping when unquoted.
I believe that is all the characters in paths that need escaping, but they aren't explicitly mentioned in the GLib documentation, and might change in the future. Maybe that's why I should try resolve the issues with quotes in paths when quoting is turned on? (The one in #3011 > Other information)
> Actions: Escape number signs (#)

- eel/eel-string.c
- eel/eel-string.h
- libnemo-private/nemo-action.c
In actions, when quoting is enabled, the quotes in paths, double or single, were not handled at all. This led to incorrect handling for paths with quotes and/or backslashes.
For instance, if `Quote=single` is in the actions file, and the target file path contains a `'` character, then the command parsing becomes incorrect starting at where that quote is.
Actioning on a file `/home/veractor/Pictures/Katie's tree.jpg`, an exec line:
test.sh %F
becomes
test.sh '/home/veractor/Pictures/Katie's tree.jpg'
Which would be interpreted as 3 arguments, `test.sh`, `/home/veractor/Pictures/Katies`, and `tree.jpg'`, where the trailing quote causes the command to not run at all.
> Actions: Escape quoted content in paths

- libnemo-private/nemo-action.c
The device paths in Actions were not escaped the same way as the normal paths, like as in some of my previous PRs. Although device file paths rarely have special characters, I think it's better to treat device paths as normal file paths too, since they essentially are. Plus, the device path was previously already affected by the `EscapeSpace` entry, so I'm just completing the picture here.
> Actions: Escape device paths in addition to file paths

- eel/eel-string.c
- eel/eel-string.h
- files/usr/share/nemo/actions/sample.nemo_action
- libnemo-private/nemo-action.c
Since spaces are only one of many to-be-escaped characters for passing on to the shell, it makes little sense to single them out. Escape them when the `Quote` field is not set to `single` or `double`, and deprecate the `EscapeSpaces` field and make it do nothing. See #3059.
> Actions: Deprecate the EscapeSpaces field

- debian/control
fixes lintian warning `W: nemo-dbg: priority-extra-is-replaced-by-priority-optional`
> debian/control(nemo-dbg): priority extra->optional

- libnemo-private/nemo-action-manager.c
- libnemo-private/nemo-action-manager.h
- src/nemo-action-config-widget.c
- src/nemo-script-config-widget.c
This is really a NixOS specific issue, I guess we are the only few distributions that can make data dir as link farm :upside_down_face: I guess I will still PR this to see if I can get some review, though TBH this PR do look dirty to me :hankey: 
Sometimes `$datadir/nemo` can be a symbolic link, this can cause menu items loaded multiple times on systems like NixOS because they are populated twice when nemo iterates `XDG_DATA_DIRS`.
- https://github.com/NixOS/nixpkgs/issues/190781
---
More context: while NixOS installs everything in their own immutable prefix, it still creates symbolic links to combine the "activated" packages together in `/run/current-system/sw/share`, and that path is also added to `XDG_DATA_DIRS`:
```
$ readlink /run/current-system/sw/share/nemo …
```
> nemo-action: readlink before populate

- src/nemo-list-model.c
I believe this single line is the source of issue #3185 - after a thumbnail icon is correctly processed at the correct scale and resolution in the chain, just before being used it's accidentally resized at this line, with only baseline icon resolution without accounting for scale.
The scale multiplier appears in the Icon View code used in the same way in this PR - as Icon Mode displays without issue, I believe this was the originally intended design.
`nemo_icon_info_get_pixbuf_at_size (icon_info, icon_size * icon_scale)`
Edit: Noting it fixes #3185 to link the PR to the bug
> Fix for List View thumbnail scaling at HiDPI (issue #3185)

- src/nemo-view.c
Fixes https://github.com/linuxmint/nemo/issues/3139
Do not update the window status while the search is loading
> Stop "Searching..." pop-up button from disappearing when opening a file #3139

- libnemo-private/nemo-file.c
I'm not 100% certain that my interpretation of this behavior was the software-intended behavior - if this is incorrect, let me know:
**Current behavior:** If the image doesn't have transparency, **or** if the image is large enough, render a frame around it.
- This means that a large-sized image with transparency will be rendered with a border - this can be very unattractive.
- This also means that a very tiny image with no transparency will have a border - I believe this is also not intended.
**Behavior with change:**
- A frame will only be applied if the image doesn't have transparency (regardless of size),
- and also won't apply the frame to tiny images, even if they don't have transparency.
- The comment was tweaked to be clear about the intended behavior (if this is correct).
> Icon frame only for non-transparent icons that are large enough

- libnemo-private/nemo-clipboard-monitor.c
- libnemo-private/nemo-file.c
- libnemo-private/nemo-file.h
- src/nemo-icon-view.c
- src/nemo-list-model.c
This is done to accommodate applications that don't support parsing special URIs.
This converts paths like `sftp://...` into their local equivalent, like `file:///run/user/1000/gvfs/sftp:...`.
> Use local URIs for drag&drop, copy/paste operations

- gresources/nemo-style-fallback-mandatory.css
Fixes the problem raised in this github discussion: [How to change contrast of selected items](https://github.com/orgs/linuxmint/discussions/46).
It only occurs with the non-mint themes (Adwaita, Adwaita-dark and HighContrast), i.e. when `nemo-style-fallback-mandatory.css` is used. The selector `.nemo-window .nemo-inactive-pane .view` incorrectly includes the background color (usually blue) of the file name of what is selected.
Adding it to the `iconview` part makes no difference, even when using the icon view in nemo.
For example, if I add to my `~/.config/gtk-3.0/gtk.css` file `iconview { background-color: #ff0000; }` I can't see a difference (even with icon view), but I can see a difference with `label { background-color: #ff0000; }`. I don't know why this is, but it's why I only …
> nemo-style-fallback-mandatory.css: Fix styling on inactive pane

- eel/eel-gtk-extensions.c
- eel/eel-gtk-extensions.h
- meson.build
- src/nemo-blank-desktop-window.c
- src/nemo-places-sidebar.c
- src/nemo-view.c
When opening the menu without the mouse (shift-F10, keyboard context  menu key) gtk_menu_popup complains about not having a parent, and pops up in the wrong location.
Using gtk_menu_popup_at_rect() with a fabricated rectangle based on the pointer location works instead.
A pleasant side effect of this is that it works around another bug where clicking off the left side of a popup fails to close the menu or change focus at all. The menu now closes fine, regardless of where the user clicks.
In X11 sessions gtk_menu_popup_at_pointer() is still used.
Fixes #3218
ref: https://bugs.kde.org/show_bug.cgi?id=453532
> eel-gtk-extensions.c: (Wayland) Fix menu popup positioning, menu closing issues.

- libnemo-private/nemo-file.c
Fixes #3268 
The commit https://github.com/linuxmint/nemo/commit/dedd5f8eeb7a7bfea9de94caf7875146b941f849 increased the thumbnail size from 128 to 256px, but a hard-coded value (updated in this PR) wasn't updated. 
The hard-coded value is in an if statement that decides if the original file (e.g. an image) should be used instead of the thumbnail, in order to avoid the thumbnail being scaled up too much. At max zoom level, the icon size is 256px, and so the if statement was checking `256 > 128 * 1.25 * scale` and then using the original image, which could be very small (as mentioned in the issue).
Somehow check whether the original file is too small, and if so never replace the thumbnail with it. This would be tricky to implement from my understanding of the code.
I've manually tested the …
> nemo-file.c: Update hard-coded value for size of thumbnails.

- libnemo-private/nemo-thumbnails.c
I've found that Nemo wasn´t generating video thumbnails whenever I was in a network share (I was using the default ffmpegthumbnailer). I was finding it weird because image thumbnails were fine.
Digging into the code I've found that we are passing the smb:// file uri to the gnome_desktop_thumbnail_factory_generate_thumbnail cinnamon-desktop function, and that in turn is calling g_filename_to_uri whenever it finds a %i in a thumbnailer. 
That was exactly the case with ffmpegthumbnailer. Image thumbnailers normally don't use the %i format, but %u instead.
Since g_filename_to_uri doesn´t support anything else than local file:// uri, I've added this code to take care of that and fix the thumbnail generation.
> Fix issue when generating video thumbnails from network shares

- libnemo-private/nemo-file-operations.c
fix https://github.com/linuxmint/nemo/issues/3152
So basically the count it was trying for was hardcoded to one, meaning it will always try the "filename (copy)" filename instead of incrementing, never completing and waiting forever, PR makes it so that it will actually track how many times it failed and try the next iteration of names, tried to make it just like the other operations
> Fix trying the same filename when moving a file with duplicate name

- libnemo-private/nemo-thumbnails.c
This fixes a regression by https://github.com/linuxmint/nemo/commit/1c526f6b829091e3121b58a321f9b956674a9d6e that causes thumbnails for local files to not be created because the thumbnailer didn't get an uri.
> Fix thumbnail creation for local files

- libnemo-private/nemo-action-manager.c
Opening `nemo 6.0.0` (but issue first seen about half year ago so it is not version specific), in the first tab of the first window, actions in context menu show up in reversed order. Order seems to be correct in further tabs and windows or after changing view mode (e.g. list -> icons).
> Fix order of actions in context menu

- eel/eel-gtk-extensions.c
- meson.build
Add `GDK_WINDOWING_WAYLAND` checks to fix compatibility with gtk+ built without wayland support.
> Make wayland dependency optional

- config.h.meson.in
- debian/control
- debian/rules
- meson.build
- meson_options.txt
- src/meson.build
- src/nemo-desktop-main.c
- src/nemo-window.c
This PR allows nemo-desktop to display desktop icons on wayland compositors that support the [layer-shell](https://wayland.app/protocols/wlr-layer-shell-unstable-v1) protocol.  It adds an optional dependency on gtk-layer-shell, which supports wlroots-based compositors such as sway, wayfire etc. If the dependency is found, then nemo will run natively on wayland.
I have been using it on [wayfire](https://wayfire.org/) and it works well.
The change is very simple and should be easy to maintain even if Wayland is not yet officially supported.
> Support drawing the desktop on wayland using gtk-layer-shell.

- libnemo-private/nemo-dnd.c
- libnemo-private/nemo-dnd.h
- libnemo-private/nemo-icon-dnd.c
- src/nemo-list-model.c
Fixes https://github.com/linuxmint/nemo/issues/3354 
New drag and drop data returned:
|                              | **Before**                       | **After**                   |
|------------------------------|--------------------------------|--------------------------------|
| **text/uri-list**            | `file:///path.ext\r\n` | `file:///path.ext\r\n` |
| **text/plain**               | `file:///path.ext\r\n` |  `/path.ext\r\n`                             |
| **text/plain;charset=utf-8** | `file:///path.ext\r\n` | `/path.ext\r\n`            |
I did not see any regression with other apps I tested this on.
Apps I tested were: discord (wayland), chromium (wayland), firefox (wayland), gajim (wayland), CLion (XWayland), discord (XWayland), nemo to nemo, gedit, gnome console.
> nemo-dnd: Have the drag and drop text data not be uris but plain paths.

- data/meson.build
This is suggested in the [xdg-shell spec](https://gitlab.freedesktop.org/wayland/wayland-protocols/-/blob/463d5cfaf37c8276826cdda48df336b9d2511ed0/stable/xdg-shell/xdg-shell.xml#L651) and makes finding the `.desktop` file from an application easier.
> nemo-desktop: use app_id as .desktop file name

- src/nemo-view.c
- src/nemo-window-menus.c
* Flatpak terminals in particular will be supported
* Closes #3372
> nemo-view.c & nemo-window-menus.c: Add support for terminals with whitespace in the exec

- eel/eel-gnome-extensions.c
A default command line with whitespace will fail to execute, either silently or with a visible error, depending on the trigger. In addition, some actions would default to launching with GNOME Terminal even when another terminal was configured as the default. This adds a default list of terminals, proper switches for execution, and a boolean for whether or not the command line sequence needs to be escaped.
Closes #2571
> eel-gnome-extensions.c: Support whitespace in execution commands

- README.md
Added information to README.md with details about history and features of Nemo.
> Update README.md with details about history and features.

- eel/eel-gnome-extensions.c
This ensures that paths are not escaped when the "Run in Terminal" option is selected.
Fixes #3420
> eel-gnome-extensions.c: Set GNOME Terminal to FALSE

- config.h.meson.in
- debian/control
- debian/rules
- meson.build
- meson_options.txt
- src/meson.build
- src/nemo-desktop-main.c
- src/nemo-window.c
Remove gtk-layer-shell until it can be implemented without regressions.
Ref: #3349
Closes linuxmint/wayland#102
Closes #3439
cc @lcolitti
> Remove gtk-layer-shell

- gresources/nemo-tree-sidebar-ui.xml
This menu item used to be there, looks like its been forgotten through the latest changes.
> tree-sidebar: Add missing properties menu item.

- libnemo-private/nemo-directory-async.c
- libnemo-private/nemo-directory-private.h
- libnemo-private/nemo-file.c
- src/nemo-desktop-main.c
- src/nemo-main.c
Fixes fa76d529 ("Remove obsolete libxml dependency").
This fixes building on NixOS with failures like `../src/nemo-main.c:42:10: fatal error: libxml/parser.h: No such file or directory`.
> Remove unused libxml headers.

- src/nemo-window-manage-views.c
In case where the parent pointer is null, nemo will crash.
It is the case when granting permission for my smartphone to connect using mtp.
> nemo-window-manage-views: fix null pointer dereference

- src/nemo-view.c
On `action_follow_symlink_callback()` and
`action_open_containing_folder_callback()` we now confirm that exactly one thing is selected.  Previously, if zero things were selected, we would segfault.
> nemo-view.c: fix crash after some shortcuts

- src/nemo-application.c
Matcha has theming specifically for nemo, so adding it to the supported themes list!
https://vinceliuice.github.io/theme-matcha.html
> Add Matcha to Supported Theme Hints

- src/nemo-main-application.c
Some scripts rely on the `--select` flag to highlight files in file managers. While `caja`, `dolphin`, and `nautilus` support this flag, `nemo` currently does not.
This simple PR adds support for the `--select` flag in `nemo`. Although `nemo` already supports selecting files by default, passing `--select` currently triggers an argument parser error.
With this change, `--select` will be accepted by `nemo` without errors, improving compatibility with scripts expecting this flag.
> add --select compatibility flag
